"""post image

Revision ID: d1a3b0f46455
Revises: eb4a2a54080b
Create Date: 2025-06-22 12:57:31.885897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1a3b0f46455'
down_revision: Union[str, Sequence[str], None] = 'eb4a2a54080b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'tg_image_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'tg_image_id',
               existing_type=sa.String(length=255),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
